//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Unit
    {
        public int unit_id { get; set; }
        public string unit { get; set; }
        public int c_id { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
